INSERT INTO COMPANY_PROFILE (COMPANY_REGISTRATION,TRADING_NAME,NAME,EMAIL,CONTACT,EXPERIENCE)
VALUES ('1190/359/2001','Trading co','Trading holdings','info@trading.co.za','0780780781','1y4m');

INSERT INTO WORKING_HOURS (DAY_OF_THE_WEEK,START_TIME,END_TIME)
VALUES ('Monday',parsedatetime('09:00', 'hh:mm'),parsedatetime('17:00', 'hh:mm'));

INSERT INTO COMPANY_WORKING_HOURS(COMPANY_COMPANY_REGISTRATION,WORKING_HOURS_DAY_OF_THE_WEEK,WORKING_HOURS_START_TIME,WORKING_HOURS_END_TIME)
VALUES('1190/359/2001','Monday',parsedatetime('09:00', 'hh:mm'),parsedatetime('17:00', 'hh:mm'));

--with a as (select * from COMPANY_PROFILE),b as (select * from WORKING_HOURS)
--INSERT INTO COMPANY_WORKING_HOURS(COMPANY_COMPANY_REGISTRATION,WORKING_HOURS_DAY_OF_THE_WEEK,WORKING_HOURS_END_TIME,WORKING_HOURS_START_TIME)
--VALUES((SELECT COMPANY_REGISTRATION FROM A), (select DAY_OF_THE_WEEK from WORKING_HOURS),(select END_TIME from WORKING_HOURS),(select START_TIME from WORKING_HOURS));

--with a as (select * from COMPANY_PROFILE), b as (select * from WORKING_HOURS)
--INSERT INTO COMPANY_WORKING_HOURS(COMPANY_COMPANY_REGISTRATION,WORKING_HOURS_DAY_OF_THE_WEEK,WORKING_HOURS_END_TIME,WORKING_HOURS_START_TIME)
--VALUES(a.COMPANY_REGISTRATION , SELECT DAY_OF_THE_WEEK FROM b, SELECT END_TIME FROM b,SELECT START_TIME FROM b);


--INSERT INTO COMPANY_WORKING_HOURS(COMPANY_COMPANY_REGISTRATION,WORKING_HOURS_DAY_OF_THE_WEEK,WORKING_HOURS_END_TIME,WORKING_HOURS_START_TIME)
--VALUES('1190/359/2001','Monday',parsedatetime('09:00', 'hh:mm'),parsedatetime('17:00', 'hh:mm'));
--INSERT INTO CUSTOMER_PROFILE(NAME,SURNAME,EMAIL,CONTACT)
--VALUES ('John','Doe','john@doe.co','0780780781');
--INSERT INTO COMPANY_WORKING_HOURS(COMPANY_COMPANY_REGISTRATION,WORKING_HOURS_DAY_OF_THE_WEEK,WORKING_HOURS_END_TIME,WORKING_HOURS_START_TIME)


-- private String dayOfTheWeek;
--    @JsonFormat(pattern = "HH:mm", shape = JsonFormat.Shape.STRING)
--    private Date startTime;
--    @JsonFormat(pattern = "HH:mm", shape = JsonFormat.Shape.STRING)
--    private Date endTime;
--private String name;
--    private String surname;
--    @Id
--    private String email;
--    private String contact;